#!/bin/bash

#  _
# | |
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           | |
#           |_|

function autostart() {
    local app="$1"
    shift
    pgrep -x "$app" > /dev/null || "$app" $@
}

bspc config border_width 1
bspc config window_gap 6
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config left_padding 220
bspc config right_padding 220
bspc config top_padding 120
bspc config bottom_padding 120
bspc config left_monocle_padding -210
bspc config right_monocle_padding -210
bspc config top_monocle_padding -110
bspc config bottom_monocle_padding -80
bspc monitor -d $(seq -s ' ' 10)

bspc config split_ratio 0.6
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config honor_size_hints true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color "#3b4252"
bspc config active_border_color "#434c5e"
bspc config focused_border_color "#d8dee9"
bspc config presel_feedback_color "#81a1c1"

betterlockscreen -w &
xsetroot -cursor_name left_ptr &

autostart picom &
autostart sxhkd &
$HOME/.config/polybar/launch_polybar.sh &
(autostart mpd && killall -qe mpd-notification ; mpd-notification -m $HOME/Music -p 6600) &
(killall -qe dunst ; dunst) &
autostart unclutter --timeout 3 --jitter 2 --exclude-root --ignore-scrolling &
autostart udiskie -ansF &
autostart redshift-gtk -P &
autostart nm-applet &
autostart blueman-applet &
