#!/bin/sh

#  _
# | |
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           | |
#           |_|

bspc config border_width 2
bspc config window_gap 10

i=1
for monitor in $(bspc query -M); do
    bspc monitor $monitor -n "$i" -d $i/{1,2,3,4,5,6,7,8,9,10}
    let i++
done
unset i

bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config normal_border_color "#3c3836"
bspc config active_border_color "#3c3836"
bspc config focused_border_color "#928374"
bspc config urgent_border_color "#cc241d"
bspc config presel_feedback_color "#fabd2f"

feh --bg-fill $HOME/.config/bspwm/wallpaper.jpg &
xsetroot -cursor_name left_ptr &

(killall -qe sxhkd ; sxhkd) &
$HOME/.config/bspwm/launch_polybar.sh &
(killall -qe dunst ; dunst) &
(killall -qe udiskie ; udiskie -ansF) &
(killall -qe blueman-applet ; blueman-applet) &
(killall -qe nm-applet ; nm-applet) &
(killall -qe redshift-gtk ; redshift-gtk) &
