#!/bin/sh

#  _
# | |
# | |__  ___ _ ____      ___ __ ___
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           | |
#           |_|

bspc config border_width 2
bspc config window_gap 10

# bspc monitor -d $(seq -s ' ' 10)
$HOME/.config/bspwm/multimonitor.sh

bspc config split_ratio 0.5
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color "#3c3836"
bspc config active_border_color "#3c3836"
bspc config focused_border_color "#928374"
bspc config presel_feedback_color "#fabd2f"

feh --bg-fill $HOME/.config/bspwm/wallpaper.jpg &
xsetroot -cursor_name left_ptr &

(killall -qe sxhkd ; sxhkd) &
(killall -qe polybar ; $HOME/.config/bspwm/launch_polybar.sh) &
# (killall -qe polybar ; polybar top) &
(killall -qe mpd ; mpd ; killall -qe mpd-notification ; mpd-notification -m $HOME/Music -p 6600) &
(killall -qe dunst ; dunst) &
(killall -qe udiskie ; udiskie -ansF) &
(killall -qe blueman-applet ; blueman-applet) &
(killall -qe nm-applet ; nm-applet) &
(killall -qe redshift-gtk ; redshift-gtk) &
